---
- hosts: ciber-react
  become: yes
  pre_tasks:
    - apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present
    - apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

    - name: Install Packages
      apt: pkg={{ item }} state=installed update_cache=yes
      with_items:
        - rabbitmq-server
        - python
        - python-dev
        - python-pip

    - name: Enable services
      service: name={{ item }} enabled=yes state=restarted
      with_items:
        - rabbitmq-server

    - command: rabbitmq-plugins enable rabbitmq_management
    - command: rabbitmqctl -q add_user {{ rabbitmq_username }} {{ rabbitmq_password }}
      ignore_errors: yes

    - name: Python environment
      pip: name={{ item }}
      with_items:
        - celery
        - paho-mqtt
        - requests
        - docopt
        - gevent

    - name: create directories
      become: no
      file: path=~/react/workers state=directory

    - name: Deploy code
      become: no
      copy: src=../react/{{ item }} dest=~/react/{{ item }}
      with_items:
        - listener.py
        - workers/__init__.py
        - workers/celery.py
        - workers/tasks.py

    - name: Install upstart scripts
      template: src=listener.conf.j2 dest=/etc/init/listener.conf
    - template: src=workers.conf.j2 dest=/etc/init/workers.conf
    - command: initctl reload-configuration

    - name: Enable services
      service: name={{ item }} enabled=yes state=restarted
      with_items:
        - listener
        - workers
