---
- hosts: ciber-react
  become: yes
  tasks:
    - apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present
    - apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

    - name: Install Packages
      apt: pkg={{ item }} state=installed update_cache=yes
      with_items:
        - rabbitmq-server
        - python
        - python-dev
        - python-pip
        - python-lxml
        - libxml2-dev
        - libxslt-dev
        - git

    - name: Configure RabbitMQ
      template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config

    - name: Enable and restart RabbitMQ
      service: name={{ item }} enabled=yes state=restarted
      with_items:
        - rabbitmq-server

    - command: rabbitmq-plugins enable rabbitmq_management
    - command: rabbitmqctl -q add_user {{ rabbitmq_username }} {{ rabbitmq_password }}
      ignore_errors: yes

    - name: Python environment
      pip: name={{ item }}
      with_items:
        - celery
        - paho-mqtt
        - requests
        - requests-toolbelt
        - docopt
        - gevent
        - PyLD
        - pyyaml
        - jsonpath-rw
        - flower
        - lxml
        - BeautifulSoup4

    - name: Clone Indigo Client
      git: repo=http://bitbucket.org/archivea/indigo-cli.git dest=/opt/indigo-cli

    - name: Install Indigo dependencies
      pip: requirements=/opt/indigo-cli/requirements.txt

    - name: Install Indigo client
      pip: name='file:///opt/indigo-cli'

    - name: create directories
      become: no
      file: path=~/react/workers state=directory

    - name: Deploy code
      become: no
      copy: src=../react/{{ item }} dest=~/react/ mode=0755
      with_items:
        - listener.py
        - traverse.py
        - workers
        - index
      tags: code

    - name: Install upstart scripts
      template: src=listener.conf.j2 dest=/etc/init/listener.conf
    - template: src=workers.conf.j2 dest=/etc/init/workers-{{item.name}}.conf
      with_items:
        - {name: high, workers: 4, queues: "default"}
        - {name: low, workers: 1, queues: "traversal"}
    - template: src=flower.conf.j2 dest=/etc/init/flower.conf
    - command: initctl reload-configuration

    - name: Restart services
      service: name={{ item }} state=restarted
      with_items:
        - listener
        - workers-high
        - workers-low
        - flower
      tags: code
